### ISSUE TITLE
Support for Django 4

### ISSUE THREAD

**Issue by benoit9126** [llybin/drf-recaptcha#14]
Currently, this package supports Django until the versions 3.2. Is it possible to add a support for [Django 4.0](https://docs.djangoproject.com/en/4.0/releases/4.0/)?

**Comment by llybin** [comment]
Yep, you can make PR like that: https://github.com/llybin/drf-recaptcha/commit/5e93cd8d3dbd2b3db698746a1eb6e57d44776a01
