### ISSUE TITLE
How to use properly

### ISSUE THREAD

**Issue by Larcis** [llybin/drf-recaptcha#3]
Hi Ilybin, I am a newbie in django and django rest framework. I am trying to use a recaptcha v2  from a mobile app. I tried to use your package but I couldn't figure out how. I inspected code but no luck.  If it's okay for you can you  please provide an example endpoint function that uses v2 serializer, that will help me a ton. Thanks.

**Comment by llybin** [comment]
Hi, look this project, so just add in serializer and define your key in settings:

https://github.com/TranslateForSG/translateforsg-backend/blob/develop/translations/serializers.py#L71

https://github.com/TranslateForSG/translateforsg-backend/blob/develop/translateforsg/settings.py#L178

**Comment by Larcis** [comment]
thanks. I think the error was due my django version. i used it like

```
    ss = CaptchaSerializer(context={"request": request}, data=request.data)
    if ss.is_valid():
        return Response({"recaptcha": "OK"}, status=status.HTTP_202_ACCEPTED)
    return Response(ss.errors, status=status.HTTP_400_BAD_REQUEST)
```

and problem solved.
