### ISSUE TITLE
Logger causes Sentry issue

### ISSUE THREAD

**Issue by simon-ccoms** [llybin/drf-recaptcha#37]
The use of logger.error in validators causes an issue to be created in my Sentry integration whenever a recaptcha field fails for whatever reason.

I don't really care about these failures, as it's probably nothing to do with me - it's probably a valid reason for failure (score too low or whatever) - so I don't really want a new issue to be generated every time it happens. But I can't switch off the logger.

**Comment by llybin** [comment]
```python
            logger.error(
                "ReCAPTCHA validation failed due to value of action '%s'"
                " is not equal with defined '%s'.",
                action,
                self.recaptcha_action,
            )
```
perhaps it should be warning or even info level.

**Comment by simon-ccoms** [comment]
Yeah, that should work. There's a couple of logger.error calls in that module - I'm getting caught on one of the others but I guess they should all be info level.

**Comment by llybin** [comment]
let's see

http errors/request fails, I think it's an error

```python
        logger.error(
            "ReCAPTCHA validation failed due to: %s",
            check_captcha.error_codes,
        )
        raise ValidationError(self.messages["captcha_invalid"], code="captcha_invalid")
```

it's probably the wrong key, nothing will work expected, imho it's an error
```python
            logger.error(
                "The response contains score, reCAPTCHA v2 response doesn't"
                " contains score, probably secret key for reCAPTCHA v3",
            )
            raise ValidationError(self.messages["captcha_error"], code="captcha_error")
```

it's probably the wrong key, nothing will work expected, imho it's an error
```python
            logger.error(
                "The response not contains score, reCAPTCHA v3 response must"
                " contains score, probably secret key for reCAPTCHA v2",
            )
            raise ValidationError(self.messages["captcha_error"], code="captcha_error")
```

it's INFO, sure it's not an error, this is legitimate logic
```python
            logger.error(
                "ReCAPTCHA validation failed due to score of %s"
                " being lower than the required amount for action '%s'.",
                self.score,
                action,
            )
```

data sent for validation for another action, configuration problem/hackers/client bug/something similar like that
warning?
```python
            logger.error(
                "ReCAPTCHA validation failed due to value of action '%s'"
                " is not equal with defined '%s'.",
                action,
                self.recaptcha_action,
            )
```

**Comment by simon-ccoms** [comment]
That first one is the one I'm getting a lot of and it's not the wrong key. It's "browser error" which is some sort of network failure, I think. So not a lot I can do about it and the user can just try again and hope. Either way, I don't want it to cause an issue that I have to try and fix because I can't fix it.

**Comment by llybin** [comment]
"ReCAPTCHA validation failed due to: %s", -- this one? what is in the details?

**Comment by simon-ccoms** [comment]
ReCAPTCHA validation failed due to: ["browser-error"]

**Comment by llybin** [comment]
https://www.googlecloudcommunity.com/gc/reCAPTCHA-Enterprise/Why-Getting-reCAPTCHA-browser-error-on-iPhone/m-p/719804

ok I will fix it

**Comment by llybin** [comment]
please check https://github.com/llybin/drf-recaptcha/releases/tag/4.0.0

**Comment by llybin** [comment]
I will create a release with this change from previous version tomorrow

**Comment by llybin** [comment]
![Screenshot_20240911-222629](https://github.com/user-attachments/assets/2c2fcc29-f735-421e-8d39-139f2af38005)

**Comment by simon-ccoms** [comment]
Yeah, we're way behind - long story - we're on Django 2.2.9!

**Comment by llybin** [comment]
Sorry, but support of 2.2 was removed 2 years ago https://github.com/llybin/drf-recaptcha/commit/d71a3789f044b7f87638891817c688d6ee0473e5

the time to ask bosses to make time to upgrade a stack :)

**Comment by llybin** [comment]
There are 5 options:
1. But you will mute real errors
```python
LOGGING = {
    ...
    'loggers': {
        'drf_recaptcha: {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
```
2. Mute in Sentry this error
3. Sentry allow pre filter messages, see Sentry doc
4. Upgrade to 4.2 Django 
5. Monkey patch validator functions
