### ISSUE TITLE
Failing support for Django 5.1

### ISSUE THREAD

**Issue by mliezun** [llybin/drf-recaptcha#40]
Hi!

Thanks for the project.

I was trying to use it with Django 5.1 and got the following error:

```
Because drf-recaptcha (4.0.1) depends on django (>=4.2,<5.0)
 and <project> depends on django (5.1.0), drf-recaptcha is forbidden.
So, because <project> depends on drf-recaptcha (4.0.1), version solving failed.
```

Here's a copy of my dependencies:

```
[tool.poetry.dependencies]
python = "^3.11"
django = "5.1.0"
whitenoise = "^6.7.0"
psycopg2-binary = "^2.9.9"
django-admin-env-notice = "^1.0"
django-environ = "^0.11.2"
django-structlog = "^8.1.0"
django-recaptcha = "^4.0.0"
django-templated-mail = "^1.1.1"
djangorestframework = "^3.15.2"
backoff = "^2.2.1"
python-dateutil = "^2.9.0.post0"
gunicorn = "^23.0.0"
django-health-check = "^3.18.3"
drf-recaptcha = "4.0.1"
```

**Comment by KOliver94** [comment]
I think this line is the problem as caret requirements only allow until the next major version which is `< 5.0` in this case.

https://github.com/llybin/drf-recaptcha/blob/adcf44f70e51b03e474386cc69e630100faccbaa/pyproject.toml#L45

I think `django = ">= 4.2"` should work.

**Comment by mliezun** [comment]
I made a PR #41 to make it easier for you @llybin.

**Comment by mliezun** [comment]
Thank you @llybin!!

**Comment by llybin** [comment]
@mliezun, thank you, have a nice Monday :)
